### ISSUE TITLE
Meetup Events

### ISSUE THREAD

**Issue by caseywatts** [techcorridorio/techcorridorio.github.io#3]
### An Example

For an example done in angular, we can reference NewHaven.io's site
- [angular controller](https://github.com/newhavenio/newhavenio-website/blob/master/app/scripts/controllers/meetup.js) (with the GET request string example)
- [angular service](https://github.com/newhavenio/newhavenio-website/blob/master/app/scripts/services/meetupService.js)
### HTML markup

We can make something similar to NewHaven.io's event cards using [bootstrap panels](getbootstrap.com/components/#panels) to start. Static HTML is fine for the first pass, we can make it into an actual template later.
### Getting The Data

We can form our own GET requests by hand, it's just one URL format we'll have to deal with.
[GET /2/events API docs](http://www.meetup.com/meetup_api/docs/2/events/)
### Authentication

For authentication, we can use a raw `API key` for local development (get yours [here](https://secure.meetup.com/meetup_api/key/)), but we'll want a [`signed API key`](http://www.meetup.com/meetup_api/auth/#keysign) for the specific GET request query that will be shared publicly. We'll want to document something about how to produce this in our README.
### Data Modeling

How should we loop through the data to show it on the page? 
- `underscore.js` with templates
- raw javascript
- angular (probably not lol)

**Comment by benjaminoakes** [comment]
Thanks for thinking through this!  I got stuck on the templating.  There are a few too many ways to do it.  I was tempted to use jQuery templates, but those were deprecated.

The goal is to make this project very approachable to any developer, and I think that includes using very popular technologies.  Examples: jQuery, Bootstrap, etc.  I think Mustache/Handlebars templates might be the most popular/approachable of the choices I'm aware of.  There might be a better one though...

**Comment by uncompiled** [comment]
There are lots of ways to do this, but I started off with jQuery+Bootstrap, since it was already present.

To use it, you'd have to create a `<div id="#meetup-events">` somewhere in the HTML, include [meetup-events.js](https://github.com/uncompiled/techcorridorio.github.io/blob/master/js/meetup-events.js), create a Meetup object with a key-signed URL (and the maximum number of events to display) and call [getEvents()](https://github.com/uncompiled/techcorridorio.github.io/blob/master/_layouts/meetups.html). It ends up looking like [this](http://www.uncompiled.org/techcorridorio.github.io/meetups.html).

I agree that Mustache/Handlebars are probably the most popular Javascript templates, but I'm also thinking that it would be good as a web component. As a user (developer), it would be nice to simply insert a custom element like `<meetup-event group="techcorridorio" ... >`.

**Comment by benjaminoakes** [comment]
My only thought is that it needs to be approachable, even to newbies -- and hopefully reusable too.  I think this is good in those respects.

I think the component idea is interesting... I think we should try that.

I'd love a pull request for this, when you have a chance.  Thanks so much for doing this!

**Comment by uncompiled** [comment]
I'm going to work on a meetup component and see where that goes.

**Comment by caseywatts** [comment]
a meetup component is created, pr'd, merged, and out for a while :)
Closing the issue!
